package com.inn.counselling.utils;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;
/**
 * Represents the container for the results of advance search. This container
 * also keeps meta data information about the limits used for pagination.
 * Any other information specific to results shall be placed in this.
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 * @param <Entity> represents the Entity type
 */
@XmlRootElement(name="result")
public class AdvanceSearchResult<Entity> {
  public static final String leftBrace="{";
	  public static final String rightBrace="}";
	
	/**
	 * represents the upper limit on the number of records fetched.
	 */
	private long upperBound;
	/**
	 * represents the lower limit on the number of records fetched.
	 */
	private long lowerBound;
	/**
	 * represents the total records found for the given query.
	 */
	private long totalRecords;
	/**
	 * represents the list of actual records fetched from the persistence store.
	 */
	private List<Entity> results;
	/**
	 * @return returns the upper limit on the number of records fetched.
	 */
	public long getUpperBound() {
		return upperBound;
	}
	/**
	 * sets the the upper limit on the number of records fetched.
	 * @param upperBound
	 */
	public void setUpperBound(long upperBound) {
		this.upperBound = upperBound;
	}
	/**
	 * @return returns the lower limit on the number of records fetched.
	 */
	public long getLowerBound() {
		return lowerBound;
	}
	/**
	 * sets the lower limit on the number of records fetched.
	 * @param lowerBound 
	 */
	public void setLowerBound(long lowerBound) {
		this.lowerBound = lowerBound;
	}
	/**
	 * @return returns the total records found for the given query.
	 */
	public long getTotalRecords() {
		return totalRecords;
	}
	/**
	 * sets the total records found for the given query.
	 * @param totalRecords
	 */
	public void setTotalRecords(long totalRecords) {
		this.totalRecords = totalRecords;
	}
	/**
	 * @return returns the list of actual records fetched from the persistence store.
	 */
	public List<Entity> getResults() {
		return results;
	}
	/**
	 * sets the list of actual records fetched from the persistence store.
	 * @param results
	 */
	public void setResults(List<Entity> results) {
		this.results = results;
	}
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append(leftBrace).
		append("UpperBound:").append(getUpperBound()).
		append(",LowerBound:").append(getLowerBound()).
		append(",TotalRecords:").append(getTotalRecords()).
		append(",Result:").append(getResults()).
		append(rightBrace);
		return builder.toString();
	}
}
