package com.inn.counselling.security.mgmt;

/**
 * Represents constants declared for Password expiration and associated features.
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public class PasswordExpiryConstants 
{
	/**
	 * represents the date time format. 
	 */
	public static final String DATE_FORMAT = "MM/dd/yy HH:mm:ss";
	/**
	 * represents the password management service bean name.
	 */
	public static final String PSWD_MGMT_SERVICE_BEAN_NAME = "passwordMgmtServiceBean";
	/**
	 * represents the query name for fetching the features associated with
	 * password expiration. 
	 */
	public static final String FEATURE_FETCH_QUERY = "featureFetchQuery";
	/**
	 * represents the query name for fetching the details associated to password
	 * expiry for a given user. 
	 */
	public static final String DETAILS_FETCH_QUERY = "detailsFetchQuery";

	/////////////////////// PASSWORD FEATURES CONSTANTS //////////////////////////
	/**
	 * represents the first time login feature. 
	 */
	public static final String FIRST_TIME_CHANGE = "first_time_change";
	/**
	 * represents password expiry feature.
	 */
	public static final String PASSWORD_EXPIRY = "expiration_interval";

	/////////////////////// PASSWORD EXPIRY DETAILS CONSTANTS //////////////////////////
	/**
	 * represents identifier for maximum number of allowed unsuccessful login attempts. 
	 */
	public static final String FAILED_LOGIN_ATTEMPTS = "failed_attempts"; 
	/**
	 * represents identifier for locked status 
	 */
	public static final String LOCKED = "locked";
	/**
	 * represents indentifier for the date when the password was last updated. 
	 */
	public static final String LAST_UPDATED_DT = "last_updated_dt";
	/**
	 * represents identifier for encoded password field. 
	 */
	public static final String PASSWORD= "password";
	/**
	 * represents identifier for comma separated password history.
	 */
	public static final String PASSWORD_HISTORY = "history";
	/**
	 * represents identifier representing if user logging in for the first time. 
	 */
	public static final String IS_FIRST_TIME_LOGIN = "first_time_login";
	/**
	 * represents identifier representing days left in expiry of password. 
	 */
	public static final String EXPIRY_DAYS_LEFT = "expiry_days_left";
	/**
	 * represent identifier for change password error messages.
	 */
	public static final String ERROR_MESSAGES = "error_messages";
	/**
	 * represent identifier for attempts left for login.
	 */
	public static final String ATTEMPTS_LEFT = "attempts_left";
	/**
	 * represents different possible action after post authentication.
	 */
	public static enum PostAuthenticationAction{
		/**
		 * represents user account is locked.
		 */
		LOCKED,
		/**
		 * represents password is expired 
		 */
		PASSWORD_EXPIRED, 
		/**
		 * represents password change notification is switched ON.
		 */
		NOTIFY,
		/**
		 * represents user must be forced to first time login.
		 */
		FIRST_TIME_LOGIN,
		/**
		 * represents the normal flow.
		 */
		NORMAL,
		/**
		 * represents condition that user does not exist with given name.
		 */
		ERR_USER_NOT_EXIST,
		/**
		 * represents identifier for normal authentication error.
		 */
		NORMAL_AUTH_ERR
	}

	/**
	 * represents different possible condition for persisting the detail bean.
	 */
	public static enum PersistDetailBeanCondition{
		/**
		 * represents identifier for successful authentication.
		 */
		AUTH_SUCCESS,
		PASS_CHANGE,
		/**
		 * represents identifier for authentication failure.
		 */
		AUTH_FAILURE,
		/**
		 * represents identifier for resting the login attempts.
		 */
		ATTEMPT_RESET
	}
}

