package com.inn.counselling.dao.criteria.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.inn.counselling.dao.annotation.CriteriaExecutor;
import com.inn.counselling.dao.criteria.IQueryExecutor;

/**
 * Hibernate implementation for query execution service. Executes the criteria 
 * generated by {@link HibernateCriteriaBuilder}.
 * 
 * @param <Entity>
 */
@CriteriaExecutor
public class HibernateQueryExecutor<Entity> implements IQueryExecutor<Entity> {
	
	private static final Logger logger = LoggerFactory.getLogger(HibernateQueryExecutor.class);
	/**
	 * returns the list of entities filtered after applying criteria.
	 */
	public List<Entity> select(Object criteria) {
		logger.debug("Entry inside @class HibernateQueryExecutor @method select @param criteria");
		Criteria hibernateCriteria = (Criteria) criteria;
		return hibernateCriteria.list();
	}
	/**
	 * @return int returns the total count of entities filtered using provided criteria.
	 */
	public int count(Object criteria) {
		logger.debug("Entry inside @class HibernateQueryExecutor @method count @param criteria");
		return	this.select(criteria).size();
	}

}
